Setting.json with source_scanner selection #101
fosslight/fosslight_scanner pull request #109
Opened 2024-07-21 07:51 UTC by soonhong99

## Description

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-07-22 05:47 UTC, soimkim commented on src/fosslight_scanner/_parse_setting.py
> +            strings[i] = ''
그러네요!

2024-07-22 05:47 UTC, soimkim commented on src/fosslight_scanner/_parse_setting.py
> +            booleans[i] = False
Agree

2024-07-22 05:50 UTC, soimkim commented on src/fosslight_scanner/fosslight_scanner.py
> +                                              f"--selected_scanner {selected_source_scanner}")
이건 빼주십시오. fosslight_scanner parameter에는 selected_scanner 없음

2024-07-31 15:10 UTC, soonhong99 commented
setting.json 관련 scanner source -s 옵션 구현 완료 하였습니다.

확인해주세요~

2024-08-02 08:49 UTC, soonhong99 commented
setting.json 관련 scanner source -j 옵션 구현 완료 하였습니다.

Can Generate raw result of scanners in json format At Your Setting.json

2024-08-03 04:55 UTC, soimkim commented on setting.json
이 파일은 삭제해주십시오.
tests/setting.json 에 추가된 paramter를 넣어 주십시오.

2024-08-03 04:55 UTC, soimkim commented
PR의 Description에 수정한 사항에 대한 설명을 작성해주십시오.

2024-08-03 04:58 UTC, soimkim commented
tox -e release시 에러가 없는지 확인해주십시오. (컨벤션 룰 에러도 출력됩니다.)

2024-08-04 11:41 UTC, soonhong99 commented
관련 내역 수정 완료 및 description 부분에 코드 설명 넣어놨습니다.

2024-08-05 04:31 UTC, soimkim commented on src/fosslight_scanner/fosslight_scanner.py
> +                                              f"--selected_scanner {selected_source_scanner}")
@soonhong99 님, 수정 완료된 커맨트는 Resolve Conversation 클릭 부탁드립니다.
![image](https://github.com/user-attachments/assets/09f9a039-c870-4412-ab09-b924025df0d3)

2024-08-05 04:41 UTC, soimkim commented on src/fosslight_scanner/cli.py
> +        (mode, path, dep_argument, output, format, link, db_url, timer, raw,
mode 앞,  source_write_json_file 뒤 중괄호가 불필요합니다.

2024-08-05 04:43 UTC, soimkim commented on tests/setting.json
> +  "path": ["/Users/hongggggg/noCloudProgramming/FL_example/example"],
추후 tox에서 실행 가능하도록 절대 경로가 아닌 상대경로를 입력해주십시오.
기존 "tests"폴더로 유지하는 것을 제안드립니다.

2024-08-05 04:44 UTC, soimkim commented on src/fosslight_scanner/_parse_setting.py
> +    return (
( 추가하신 사유 문의드립니다.

2024-08-05 04:52 UTC, soimkim commented on src/fosslight_scanner/_parse_setting.py
> +    return (
https://realpython.com/python-return-statement/ 참고하시면 multiple 변수를 return할 때, ()가 필요없음을 확인하실 수 있습니다. 

Note: You can build a Python tuple by just [assigning](https://realpython.com/python-assignment-operator/) several comma-separated values to a single variable. There’s no need to use parentheses to create a tuple. That’s why multiple return values are packed in a tuple.

2024-08-05 05:22 UTC, soimkim commented on src/fosslight_scanner/cli.py
> +            (s_mode, s_path, s_dep_argument, s_output, s_format, s_link,
괄호 불필요합니다.

2024-08-06 06:15 UTC, soonhong99 commented on src/fosslight_scanner/_parse_setting.py
> +    return (
글자수 제한 규칙 때문에 변경하였으나 기존 코드 그대로 유지해도 규칙에 어긋나지 않는다는 점 확인하였습니다.

2024-08-06 06:42 UTC, soonhong99 commented
관련 내용 확인 및 수정 완료 하였습니다.

2024-08-12 15:40 UTC, soonhong99 commented
commit 할 때 -s 옵션 붙혔는데도 에러가 뜨네요 ㅠㅠ

2024-08-12 15:56 UTC, soonhong99 commented
FL binary --notice 옵션에서 print license 뿐만 아닌 setting.json에서 output으로 설정한 폴더명에 license가 txt로 저장되게끔 구현하였습니다.

2024-08-18 06:41 UTC, soimkim commented
test_src 폴더 삭제 부탁드립니다.

2024-08-18 06:43 UTC, soimkim commented on src/fosslight_scanner/fosslight_scanner.py
> +def run_dependency(path_to_analyze, output_file_with_path, params="", path_to_exclude=None):
path_to_exclude=[] 이면, 하기 if 문이 불필요합니다. 

path_to_exclude=[]로 복구하고, 하기 if문 (59,60 ) 삭제 제안드립니다.

2024-08-18 06:46 UTC, soimkim commented on src/fosslight_scanner/fosslight_scanner.py
> +                                binary_simple,)
맨 끝 ,를 제거해주십시오.

2024-08-18 06:47 UTC, soimkim commented on test_src/test.py
> +print('Hello, World!')
test_src 폴더 삭제해주십시오.

2024-08-20 08:52 UTC, soonhong99 commented
관련 내용 수정 완료하였습니다.

2024-08-25 07:18 UTC, soimkim requested changes

2024-08-25 07:18 UTC, soimkim commented on src/fosslight_scanner/_parse_setting.py
> +        binary_simple,
끝에 , 제거해주세요

2024-08-25 07:18 UTC, soimkim commented on src/fosslight_scanner/cli.py
> +        binary_simple,
끝에 , 제거해주세요

2024-08-25 07:18 UTC, soimkim commented on src/fosslight_scanner/cli.py
> +                 source_time_out, binary_simple,)
끝에 , 제거해주세요

2024-08-28 12:24 UTC, soonhong99 commented
관련 내용 수정 하였습니다.

2024-08-29 01:14 UTC, soimkim commented
@soonhong99 ,
수정 완료된 사항에는 커맨트 남겨주시고 Resolve conversation 클릭 부탁드려요.
![image](https://github.com/user-attachments/assets/5133d920-7c81-4ac2-85a0-fada957044d0)

2024-08-29 08:33 UTC, soonhong99 commented on src/fosslight_scanner/_parse_setting.py
> +        binary_simple,
제거완료.

2024-08-29 08:33 UTC, soonhong99 commented on src/fosslight_scanner/cli.py
> +        binary_simple,
제거 완료

2024-08-29 08:33 UTC, soonhong99 commented on src/fosslight_scanner/cli.py
> +                 source_time_out, binary_simple,)
제거 완료.

2024-08-29 08:34 UTC, soonhong99 commented
![image](https://github.com/user-attachments/assets/e6e012a8-a0bb-4328-8fdc-332375423ce4)
resolve를 눌렀는데 커멘트를 안날리면 resolve가 되지 않나요? 
우선 커멘트도 날렸습니다.

2024-08-30 01:06 UTC, merged

2024-08-30 01:13 UTC, soimkim commented
path_to_exclude가 적용 안 되는 파생 버그가 있음